[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui" }
smallvec = { version = "1.15", features = ["const_new"] }
